---
name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [1.18, 1.19]
        os: [ubuntu-latest]

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -ldflags="-s -w" -v
        working-directory: cmd/server

      - name: Test
        run: go test -v -tags test ./...
